{"uuid": "3b72341c-c157-44ef-a715-f971afca3fe7", "children": ["54fb6a5b-90f0-49a9-bfd7-ce5767a24594", "ed90de1f-8836-400f-aadf-8fdbfa16a5e1", "001c3b20-2820-4091-a6b3-4813cb4cb39a", "3bc692b2-b033-4b58-843c-4c543b55aa1e"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=88.0.4324.182)\nStacktrace:\n0   chromedriver                        0x0000000108539e09 chromedriver + 2641417\n1   chromedriver                        0x0000000108bc54b3 chromedriver + 9503923\n2   chromedriver                        0x00000001082dc9b3 chromedriver + 162227\n3   chromedriver                        0x00000001082d66b0 chromedriver + 136880\n4   chromedriver                        0x00000001082ca30d chromedriver + 86797\n5   chromedriver                        0x00000001082cafa1 chromedriver + 90017\n6   chromedriver                        0x00000001082ca585 chromedriver + 87429\n7   chromedriver                        0x00000001082c9cd8 chromedriver + 85208\n8   chromedriver                        0x00000001082c8ed5 chromedriver + 81621\n9   chromedriver                        0x00000001082c91c3 chromedriver + 82371\n10  chromedriver                        0x00000001082de510 chromedriver + 169232\n11  chromedriver                        0x0000000108337961 chromedriver + 534881\n12  chromedriver                        0x0000000108328242 chromedriver + 471618\n13  chromedriver                        0x0000000108337446 chromedriver + 533574\n14  chromedriver                        0x0000000108328553 chromedriver + 472403\n15  chromedriver                        0x0000000108302ae4 chromedriver + 318180\n16  chromedriver                        0x0000000108303a87 chromedriver + 322183\n17  chromedriver                        0x0000000108509ab9 chromedriver + 2443961\n18  chromedriver                        0x000000010851689f chromedriver + 2496671\n19  chromedriver                        0x000000010851655b chromedriver + 2495835\n20  chromedriver                        0x00000001084f04c5 chromedriver + 2340037\n21  chromedriver                        0x000000010851747f chromedriver + 2499711\n22  chromedriver                        0x00000001084ff049 chromedriver + 2400329\n23  chromedriver                        0x000000010852e33f chromedriver + 2593599\n24  chromedriver                        0x000000010853f523 chromedriver + 2663715\n25  libsystem_pthread.dylib             0x00007fff6f522109 _pthread_start + 148\n26  libsystem_pthread.dylib             0x00007fff6f51db8b thread_start + 15\n\n", "trace": "  File \"/Library/Python/3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Python/3.8/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Python/3.8/site-packages/_pytest/fixtures.py\", line 917, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/akshaykalyanashetti/Downloads/Sel_frm_scarth2-master/conftest.py\", line 8, in test_setup\n    driver.get(\"https://app.saveo.in\")\n  File \"/Library/Python/3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 350, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/Library/Python/3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 338, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Python/3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 240, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1613571082256, "stop": 1613571085275}], "start": 1613571082256, "stop": 1613571085717}